import Login from "../../pages/login"
import Dashboard from "../../pages/dashboard"
import { time } from "systeminformation"

const dataDeHoje = new Date().toISOString().split('T')[0]

const PARCEIRO_REGISTRO = '50.071.289 DAVID DE SOUZA SILVA'

describe('Editar Registro de amostra ', () => {
    beforeEach (() => {
        Login.visitarPagina()

        Login.preencherCredenciais()

        Dashboard.vericarAcessoDashboard()
    })

        it('Acessar Registro de amostras', () => {
            cy.get('a[href="/registro-amostra"]').click()
            cy.wait(2000)
            cy.get('button[title="Criar um novo registro de amostra"]').click()
            cy.get('[data-test="registro-amostra-entrada-amostra"]')
                .should('be.disabled')
                .and('have.value', dataDeHoje)
            cy.get('[data-test="registro-amostra-safra-input"]')
                .click()
            cy.contains('li','2026/2027', {timeout: 5000})
                .should('be.visible')
                .click()
            cy.get('[data-test="registro-amostra-lote-fornecedor"]').type('123412')
            cy.get('[data-test="registro-amostra-sacas-lote"]').type('123456')
            cy.get('[data-test="registro-amostra-modalidade-compra"]').select('FUTURA')
            cy.get('[data-test="registro-amostra-certificado-input"]')
                .type('a')
            cy.contains('li', 'AAA')
                .should('be.visible')
                .click()
            cy.get('[data-test="registro-amostra-status-amostra"]')
                .should('have.attr','readonly')
            cy.get('[data-test="registro-amostra-status-amostra"]')
                .should('have.value', 'RECEBIDA')
            cy.get('[data-test="registro-amostra-cod-vendedor-input"]')
                .type('50.071.289 DAVID DE SOUZA SILVA')  
            cy.contains('li', '50.071.289 DAVID DE SOUZA SILVA').should('be.visible').click()
            cy.get('[data-test="registro-amostra-cod-corretor-input"]').type('CAROLINA TESTE - CORRETOR')
            cy.get('[data-test="registro-amostra-cod-trader-input"]')
                .clear()
                .type('Artur Logan Novo')
            cy.contains('li','Artur Logan Novo')
                .should('be.visible')
                .click() 
            cy.get('[data-test="registro-amostra-btn-salvar"]')
                .click()   
        })
        it('Registrar amostra e classificar', () => {
            cy.get('a[href="/registro-amostra"]').click()
            cy.wait(2000)
            cy.contains(PARCEIRO_REGISTRO).click()
            cy.wait(2000)
            cy.get('[data-test="qualidade-btn-acao-principal"]')
                .click()
            cy.get('[data-test="qualidade-tipo-analise"]')
                .select('Amostra de Compra')
            cy.get('[data-test="qualidade-classificador-input"]')
                .click()
            cy.contains('li', 'BEIRIGOSO')
                .should('be.visible') 
                .click()
            cy.get('[data-test="qualidade-provador-input"]')
                .click()
            cy.contains('li', 'BEIRIGOSO')
                .should('be.visible')
                .click()
            cy.get('[data-test="qualidade-data-classificacao"]')      
                .should('have.value', dataDeHoje)
            cy.get('[data-test="qualidade-status"]')
                .select('Aprovado')
            // cy.contains('li', 'Aprovado')
            //     .should('be.visible')
            //     .click()
            cy.get('[data-test="qualidade-btn-salvar"]')
                .click()
            
            cy.get('[data-test="qualidade-card-avatar"]')
                .should('be.visible')

        })

        it('Adicionar classificação', () => {
            cy.get('a[href="/registro-amostra"]').click()
            cy.wait(2000)
            cy.contains(PARCEIRO_REGISTRO).click()
            cy.wait(2000)
            cy.get('tbody tr')
                .first()
                .click()
            cy.get('[data-test="grao-btn-adicionar-classificacao"]')  
                .click()

            cy.get('[data-test="grao-tipo-cafe-autocomplete-input"]')
                .click()
            cy.contains('li', 'CAF CRU ND GA BX PD C/1200 DEF COB 01% IMP B/D S D.PEN')
                .should('be.visible')
            cy.get('[data-test="grao-padrao-autocomplete-input"]')
                .clear()
                .type('BC2')
            cy.contains('li', 'BC2')
                .should('be.visible')
                .click()
            cy.get('[data-test="pesoGramas-input"]')
                .clear()
                .type('160')
            cy.get('#TU')
                .clear()
                .type('1')
            cy.get('#PEN19')
                .clear()
                .type('10')
            cy.get('#PEN18')
                .clear()
                .type('10')
            cy.get('#PEN17')
                .clear()
                .type('10')
            cy.get('#PEN16')
                .clear()
                .type('10')
            cy.get('#PEN15')
                .clear()
                .type('10')
            cy.get('#PEN14')
                .clear()
                .type('10')
            cy.get('#PEN13')
                .clear()
                .type('10')
            cy.get('#PEN12')
                .clear()
                .type('10')
            cy.get('#PENMK09')
                .clear()
                .type('10')       
            cy.get('#PENMK10')
                .clear()
                .type('10')
            cy.get('#PENMK11')
                .clear()
                .type('10')
            cy.get('#GRINDERS')
                .clear()
                .type('10')
            cy.get('#PVA')
                .clear()
                .type('10')
            cy.get('#IMP')
                .clear()
                .type('10')
            cy.get('#FUNDO_13')
                .clear()
                .type('10')
            cy.get('#FUNDO_10')
              .clear()
              .type('10')
            cy.get('#BROCA')
                .clear()
                .type('1')
            cy.get('#FOX')
                .clear()
                .type('1')
            cy.get('[data-test="grao-finalizar-btn"]')
                .click()
            cy.get('.swal2-confirm') 
                .should('be.visible')
                .click()
        })

        it.only('Adicionar Classificação da Bebida', () => {
            cy.get('a[href="/registro-amostra"]').click()
            cy.wait(2000)
            cy.contains(PARCEIRO_REGISTRO).click()
            cy.wait(2000)
            cy.get('tbody tr')
                .first()
                .click()
            cy.get('[data-test="bebida-btn-adicionar-classificacao"]')
                .click()
            cy.get('[data-test="bebida-input-mole"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-duro"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-lrd"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-rd"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-rdr"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-rio"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-rza"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-ferm"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-sujo"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-input-verde"]')
                .clear()
                .type('10')
            cy.get('[data-test="bebida-salvar-btn"]')
                .click()
        })

        it('Classificação da Paladar', () => {
            cy.get('a[href="/registro-amostra"]').click()
            cy.wait(2000)
            cy.contains(PARCEIRO_REGISTRO).click()
            cy.wait(2000)
            cy.get('tbody tr')
                .first()
                .click()

            cy.get('[data-test="paladar-btn-adicionar-classificacao"]').click()
            
            cy.get('[data-test="paladar-switch-corpo"]').click()
            cy.get('[data-test="paladar-switch-docura"]').click()
            cy.get('[data-test="paladar-switch-sujo"]').click()
            cy.get('[data-test="paladar-switch-verde"]').click()
            cy.get('[data-test="paladar-switch-fermentado"]').click()
            cy.get('[data-test="paladar-salvar-btn"]').click()
            })

        it('Escrever observação', () => {
            cy.get('a[href="/registro-amostra"]').click()
            cy.wait(2000)
            cy.contains(PARCEIRO_REGISTRO).click()
            cy.wait(2000)
            cy.get('tbody tr')
                .first()
                .click()
            cy.get('[data-test="observacao-btn-adicionar"]').click()
            cy.get('[data-test="form-observacao-campo"]').clear().type('Observação de teste')
            cy.get('[data-test="form-observacao-btn-salvar"]').click()
            })
    })     